### ISSUE TITLE
puts has to be defined weak in 832lib 

### ISSUE THREAD

**Issue by rampa069** [minimig-dev/MinimigAGA-MiST-TC64#10]
`diff --git a/lib832/uart.c b/lib832/uart.c
index f48b727..1f77933 100644
--- a/lib832/uart.c
+++ b/lib832/uart.c
@@ -11,7 +11,7 @@ __weak int putchar(int c)
 }

-int puts(const char *msg)
+__weak int puts(const char *msg)
 {
        unsigned char c;
        int result=0;`

**Comment by robinsonb5** [comment]
Thanks for the bug report - there are some more changes to come for the staging branch which will fix this and a few other issues, but for now you can just remove the puts() function from fw/ctrl_boot_832/uart.c - it's not necessary.

**Comment by rampa069** [comment]
tnx!

**Comment by rampa069** [comment]
closed.
